# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build VoteApi/VoteApi.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test VoteApi/VoteApi.Test/VoteApi.Test.csproj --logger trx
  displayName: dotnet test
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- script: dotnet publish VoteApi/VoteApi/VoteApi.csproj --output $(Build.ArtifactStagingDirectory)
  displayName: publish artifacts
- script: npm --prefix .\vote-ui\ install .\vote-ui\
  displayName: 'installing ui packages'
- script: npm --prefix .\vote-ui\ run vue-cli-service build --dest $(Build.ArtifactStagingDirectory)/wwwroot
  displayName: 'publish ui to wwwroot'
- task: PublishBuildArtifacts@1
