# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build VoteApi/VoteApi.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test VoteApi/VoteApi.Test/VoteApi.Test.csproj --logger trx
  displayName: dotnet test
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
- script: dotnet publish VoteApi/VoteApi.sln --output $(Build.ArtifactStagingDirectory)
  displayName: publish artifacts
- task: PublishBuildArtifacts@1
